version: '3'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    ports:
      - "3001:8080"
    volumes:
      - ./open-webui:/app/backend/data
    environment:
      - WEBUI_AUTH=True
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NETWORKING_ALLOWED=True
    networks:
      - app-network
    security_opt:
      - seccomp:unconfined

  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: pipelines
    restart: always
    ports:
      - "9099:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PIPELINE_BACKEND_URL=http://open-webui:3001
      - NETWORKING_ALLOWED=True
      # Add antropic API to openwebui
      - PIPELINES_URLS="https://github.com/open-webui/pipelines/blob/main/examples/pipelines/providers/anthropic_manifold_pipeline.py"
    depends_on:
      - open-webui
    volumes:
      - ./open-webui:/app/backend/data  # Ensure pipelines have access to the same data volume
    networks:
      - app-network

volumes:
  open-webui:

networks:
  app-network:
    external: false